server.port=8087
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mybatis
mybatis.type-aliases-package=com.example.springbootmybatis.entity
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-plus
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.global-config.db-config.id-type=auto
#日志级别
logging.level.com.example.springbootmybatis=debug
logging.level.org.springframework.web=debug
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=debug
logging.level.org.mybatis=debug
logging.level.org.mybatis.spring.SqlSessionFactoryBean=debug
logging.level.org.mybatis.spring.SqlSessionTemplate=debug
logging.level.org.mybatis.spring.mapper.MapperScanner=debug
logging.level.org.mybatis.spring.mapper.MapperFactoryBean=debug
logging.level.org.mybatis.spring.mapper.SqlProvider=debug
logging.level.org.mybatis.spring.mapper.SqlProviderAdapter=debug
logging.level.org.mybatis.spring.mapper.MapperBuilderAssistant=debug
logging.level.org.mybatis.spring.mapper.MapperAnnotationBuilder=debug
